version: '3'
services: 
  playgroundwebapp: 
    restart: always
    container_name: webapp
    image: playground-webapp
    ports:
     - 4001:4000
    environment:
     NODE_ENV:  development
     APPINSIGHTS_ENABLED:  "true"