apiVersion: v1
kind: Pod
metadata:
  name: k8-playground-webapp
  labels:
        # Apply this label to pods and default
        app: k8-playground
spec:
  restartPolicy: Always
  containers:
    - name: webapp-container
      image: index.docker.io/geoffreysamper/k8s-playground:v3.0
      imagePullPolicy: Always
      envFrom:
      - configMapRef:
          name: example-config
      ports: 
        - containerPort: 4000