apiVersion: v1
kind: Pod
metadata:
  name: k8-playground-webapp
  labels:
    app: k8-playground
spec:
  restartPolicy: Always
  containers:
    - name: webapp-container
      image: index.docker.io/geoffreysamper/k8s-playground:v1.0
      imagePullPolicy: Always
      ports: 
        - containerPort: 4000